//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string PName { get; set; }
        public string PImage { get; set; }
        public decimal Salary { get; set; }
        public int PCategory { get; set; }
        public string Discraption { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
